<?php
require_once __DIR__ . '/../config.php';

/**
 * export data to CSV format
 * @param array $data Array of data to export
 * @param array $headers Column headers
 * @param string $filename Filename without extension
 */
function exportToCSV($data, $headers, $filename) {
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="' . $filename . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    // Add UTF-8 BOM for Excel
    fprintf($output, chr(0xEF).chr(0xBB).chr(0xBF));
    
    // add headers
    fputcsv($output, $headers);
    
    // add data
    foreach ($data as $row) {
        fputcsv($output, $row);
    }
    
    fclose($output);
    exit;
}

/**
 * Export data to HTML format (as a downloadable file)
 * @param array $data Array of data to export
 * @param array $headers Column headers
 * @param string $title Report title
 * @param string $filename Filename without extension
 */
function exportToPDF($data, $headers, $title, $filename) {
    // Since we don't have TCPDF installed, we'll create an HTML file instead
    header('Content-Type: text/html');
    header('Content-Disposition: attachment; filename="' . $filename . '.html"');
    
    // create a styled HTML table
    $html = '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>' . htmlspecialchars($title) . '</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        h1 { color: #333; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 10px; text-align: left; border: 1px solid #ddd; }
        th { background-color: #f5f5f5; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .footer { margin-top: 20px; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <h1>' . htmlspecialchars($title) . '</h1>
    <p>Generated on: ' . date('F j, Y g:i A') . '</p>
    <table>
        <thead>
            <tr>';
    
    // add headers
    foreach ($headers as $header) {
        $html .= '<th>' . htmlspecialchars($header) . '</th>';
    }
    
    $html .= '</tr>
        </thead>
        <tbody>';
    
    // add data
    foreach ($data as $row) {
        $html .= '<tr>';
        foreach ($row as $cell) {
            $html .= '<td>' . htmlspecialchars($cell) . '</td>';
        }
        $html .= '</tr>';
    }
    
    $html .= '</tbody>
    </table>
    <div class="footer">
        <p>Report generated by Caf Lab Admin System</p>
    </div>
</body>
</html>';
    
    echo $html;
    exit;
}

/**
 * Format data for export
 * @param array $data Raw data from database
 * @param string $type Export type (stock or sales)
 * @return array Formatted data ready for export
 */
function formatDataForExport($data, $type) {
    $formatted = [];
    
    switch ($type) {
        case 'stock':
            foreach ($data as $item) {
                $formatted[] = [
                    $item['date'],
                    $item['product_name'],
                    $item['type'],
                    $item['quantity_change'],
                    $item['category_name'],
                    '£' . number_format($item['revenue'], 2)
                ];
            }
            break;
            
        case 'sales':
            foreach ($data as $item) {
                $formatted[] = [
                    $item['date'],
                    $item['order_count'],
                    $item['items_sold'],
                    '£' . number_format($item['revenue'], 2)
                ];
            }
            break;
    }
    
    return $formatted;
}

/**
 * Get export headers based on report type
 * @param string $type Report type (stock or sales)
 * @return array Headers for export
 */
function getExportHeaders($type) {
    switch ($type) {
        case 'stock':
            return ['Date', 'Product', 'Transaction Type', 'Quantity Change', 'Category', 'Revenue'];
            
        case 'sales':
            return ['Date', 'Orders', 'Items Sold', 'Revenue'];
            
        default:
            return [];
    }
}
?>
